# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auth_mgmt_pb2 as auth__mgmt__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_mgmt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEmailValidationCode = channel.unary_unary(
                '/auth_mgmt.AuthManagement/CreateEmailValidationCode',
                request_serializer=auth__mgmt__pb2.CreateEmailValidationCodeRequest.SerializeToString,
                response_deserializer=auth__mgmt__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.VerifyEmailValidationCode = channel.unary_unary(
                '/auth_mgmt.AuthManagement/VerifyEmailValidationCode',
                request_serializer=auth__mgmt__pb2.VerifyEmailValidationCodeRequest.SerializeToString,
                response_deserializer=auth__mgmt__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.ResetPasswordByEmailValidationCode = channel.unary_unary(
                '/auth_mgmt.AuthManagement/ResetPasswordByEmailValidationCode',
                request_serializer=auth__mgmt__pb2.ResetPasswordByEmailValidationCodeRequest.SerializeToString,
                response_deserializer=auth__mgmt__pb2.ResetPasswordByEmailValidationCodeResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/auth_mgmt.AuthManagement/CreateSession',
                request_serializer=auth__mgmt__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=auth__mgmt__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.CreateSessionV2 = channel.unary_unary(
                '/auth_mgmt.AuthManagement/CreateSessionV2',
                request_serializer=auth__mgmt__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=auth__mgmt__pb2.CreateSessionV2Response.FromString,
                _registered_method=True)
        self.GetAuthUrl = channel.unary_unary(
                '/auth_mgmt.AuthManagement/GetAuthUrl',
                request_serializer=auth__mgmt__pb2.GetAuthUrlRequest.SerializeToString,
                response_deserializer=auth__mgmt__pb2.GetAuthUrlResponse.FromString,
                _registered_method=True)


class AuthManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEmailValidationCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEmailValidationCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPasswordByEmailValidationCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSessionV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEmailValidationCode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmailValidationCode,
                    request_deserializer=auth__mgmt__pb2.CreateEmailValidationCodeRequest.FromString,
                    response_serializer=auth__mgmt__pb2.EmptyResponse.SerializeToString,
            ),
            'VerifyEmailValidationCode': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEmailValidationCode,
                    request_deserializer=auth__mgmt__pb2.VerifyEmailValidationCodeRequest.FromString,
                    response_serializer=auth__mgmt__pb2.EmptyResponse.SerializeToString,
            ),
            'ResetPasswordByEmailValidationCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPasswordByEmailValidationCode,
                    request_deserializer=auth__mgmt__pb2.ResetPasswordByEmailValidationCodeRequest.FromString,
                    response_serializer=auth__mgmt__pb2.ResetPasswordByEmailValidationCodeResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=auth__mgmt__pb2.CreateSessionRequest.FromString,
                    response_serializer=auth__mgmt__pb2.CreateSessionResponse.SerializeToString,
            ),
            'CreateSessionV2': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSessionV2,
                    request_deserializer=auth__mgmt__pb2.CreateSessionRequest.FromString,
                    response_serializer=auth__mgmt__pb2.CreateSessionV2Response.SerializeToString,
            ),
            'GetAuthUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthUrl,
                    request_deserializer=auth__mgmt__pb2.GetAuthUrlRequest.FromString,
                    response_serializer=auth__mgmt__pb2.GetAuthUrlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth_mgmt.AuthManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth_mgmt.AuthManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEmailValidationCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_mgmt.AuthManagement/CreateEmailValidationCode',
            auth__mgmt__pb2.CreateEmailValidationCodeRequest.SerializeToString,
            auth__mgmt__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEmailValidationCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_mgmt.AuthManagement/VerifyEmailValidationCode',
            auth__mgmt__pb2.VerifyEmailValidationCodeRequest.SerializeToString,
            auth__mgmt__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPasswordByEmailValidationCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_mgmt.AuthManagement/ResetPasswordByEmailValidationCode',
            auth__mgmt__pb2.ResetPasswordByEmailValidationCodeRequest.SerializeToString,
            auth__mgmt__pb2.ResetPasswordByEmailValidationCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_mgmt.AuthManagement/CreateSession',
            auth__mgmt__pb2.CreateSessionRequest.SerializeToString,
            auth__mgmt__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSessionV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_mgmt.AuthManagement/CreateSessionV2',
            auth__mgmt__pb2.CreateSessionRequest.SerializeToString,
            auth__mgmt__pb2.CreateSessionV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_mgmt.AuthManagement/GetAuthUrl',
            auth__mgmt__pb2.GetAuthUrlRequest.SerializeToString,
            auth__mgmt__pb2.GetAuthUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
