# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auth_frontend_pb2 as auth__frontend__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_frontend_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthFrontendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAnonUser = channel.unary_unary(
                '/auth_frontend.AuthFrontend/CreateAnonUser',
                request_serializer=auth__frontend__pb2.CreateAnonUserRequest.SerializeToString,
                response_deserializer=auth__frontend__pb2.CreateAnonUserResponse.FromString,
                _registered_method=True)
        self.CreateAnonUserChallenge = channel.unary_unary(
                '/auth_frontend.AuthFrontend/CreateAnonUserChallenge',
                request_serializer=auth__frontend__pb2.CreateChallengeRequest.SerializeToString,
                response_deserializer=auth__frontend__pb2.CreateChallengeResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/auth_frontend.AuthFrontend/CreateSession',
                request_serializer=auth__frontend__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=auth__frontend__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.GetAuthStatus = channel.unary_unary(
                '/auth_frontend.AuthFrontend/GetAuthStatus',
                request_serializer=auth__frontend__pb2.EmptyMessage.SerializeToString,
                response_deserializer=auth__frontend__pb2.EmptyMessage.FromString,
                _registered_method=True)


class AuthFrontendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAnonUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAnonUserChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthFrontendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAnonUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAnonUser,
                    request_deserializer=auth__frontend__pb2.CreateAnonUserRequest.FromString,
                    response_serializer=auth__frontend__pb2.CreateAnonUserResponse.SerializeToString,
            ),
            'CreateAnonUserChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAnonUserChallenge,
                    request_deserializer=auth__frontend__pb2.CreateChallengeRequest.FromString,
                    response_serializer=auth__frontend__pb2.CreateChallengeResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=auth__frontend__pb2.CreateSessionRequest.FromString,
                    response_serializer=auth__frontend__pb2.CreateSessionResponse.SerializeToString,
            ),
            'GetAuthStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthStatus,
                    request_deserializer=auth__frontend__pb2.EmptyMessage.FromString,
                    response_serializer=auth__frontend__pb2.EmptyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth_frontend.AuthFrontend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth_frontend.AuthFrontend', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthFrontend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAnonUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_frontend.AuthFrontend/CreateAnonUser',
            auth__frontend__pb2.CreateAnonUserRequest.SerializeToString,
            auth__frontend__pb2.CreateAnonUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAnonUserChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_frontend.AuthFrontend/CreateAnonUserChallenge',
            auth__frontend__pb2.CreateChallengeRequest.SerializeToString,
            auth__frontend__pb2.CreateChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_frontend.AuthFrontend/CreateSession',
            auth__frontend__pb2.CreateSessionRequest.SerializeToString,
            auth__frontend__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_frontend.AuthFrontend/GetAuthStatus',
            auth__frontend__pb2.EmptyMessage.SerializeToString,
            auth__frontend__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
