# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_frontend.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth_frontend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uth_frontend.proto\x12\rauth_frontend\"\x0e\n\x0c\x45mptyMessage\"0\n\x15\x43reateAnonUserRequest\x12\x17\n\x0fuser_public_key\x18\x01 \x01(\x0c\".\n\x16\x43reateAnonUserResponse\x12\x14\n\x0c\x61non_user_id\x18\x01 \x01(\t\".\n\x16\x43reateChallengeRequest\x12\x14\n\x0c\x61non_user_id\x18\x01 \x01(\t\",\n\x17\x43reateChallengeResponse\x12\x11\n\tchallenge\x18\x01 \x01(\x0c\"\xe3\x02\n\x14\x43reateSessionRequest\x12\x44\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32/.auth_frontend.CreateSessionRequest.Credentials\x12\x12\n\nsession_id\x18\x07 \x01(\t\x12!\n\x19prompt_on_duplicate_email\x18\x08 \x01(\x08\x12\x1c\n\x14\x63\x61stle_request_token\x18\n \x01(\t\x1ap\n\x0b\x43redentials\x12R\n\x12\x65mail_and_password\x18\x01 \x01(\x0b\x32\x34.auth_frontend.CreateSessionRequest.EmailAndPasswordH\x00\x42\r\n\x0b\x63redentials\x1a>\n\x10\x45mailAndPassword\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x1b\n\x13\x63lear_text_password\x18\x02 \x01(\t\"b\n\x15\x43reateSessionResponse\x12\x16\n\x0esession_cookie\x18\x02 \x01(\t\x12\x1c\n\x14one_time_link_tokens\x18\x03 \x03(\t\x12\x13\n\x0bis_new_user\x18\x04 \x01(\x08\x32\xfe\x02\n\x0c\x41uthFrontend\x12]\n\x0e\x43reateAnonUser\x12$.auth_frontend.CreateAnonUserRequest\x1a%.auth_frontend.CreateAnonUserResponse\x12h\n\x17\x43reateAnonUserChallenge\x12%.auth_frontend.CreateChallengeRequest\x1a&.auth_frontend.CreateChallengeResponse\x12Z\n\rCreateSession\x12#.auth_frontend.CreateSessionRequest\x1a$.auth_frontend.CreateSessionResponse\x12I\n\rGetAuthStatus\x12\x1b.auth_frontend.EmptyMessage\x1a\x1b.auth_frontend.EmptyMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_frontend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYMESSAGE']._serialized_start=38
  _globals['_EMPTYMESSAGE']._serialized_end=52
  _globals['_CREATEANONUSERREQUEST']._serialized_start=54
  _globals['_CREATEANONUSERREQUEST']._serialized_end=102
  _globals['_CREATEANONUSERRESPONSE']._serialized_start=104
  _globals['_CREATEANONUSERRESPONSE']._serialized_end=150
  _globals['_CREATECHALLENGEREQUEST']._serialized_start=152
  _globals['_CREATECHALLENGEREQUEST']._serialized_end=198
  _globals['_CREATECHALLENGERESPONSE']._serialized_start=200
  _globals['_CREATECHALLENGERESPONSE']._serialized_end=244
  _globals['_CREATESESSIONREQUEST']._serialized_start=247
  _globals['_CREATESESSIONREQUEST']._serialized_end=602
  _globals['_CREATESESSIONREQUEST_CREDENTIALS']._serialized_start=426
  _globals['_CREATESESSIONREQUEST_CREDENTIALS']._serialized_end=538
  _globals['_CREATESESSIONREQUEST_EMAILANDPASSWORD']._serialized_start=540
  _globals['_CREATESESSIONREQUEST_EMAILANDPASSWORD']._serialized_end=602
  _globals['_CREATESESSIONRESPONSE']._serialized_start=604
  _globals['_CREATESESSIONRESPONSE']._serialized_end=702
  _globals['_AUTHFRONTEND']._serialized_start=705
  _globals['_AUTHFRONTEND']._serialized_end=1087
# @@protoc_insertion_point(module_scope)
