# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grok_api_pb2 as grok__api__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grok_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatStub(object):
    """── Chat ─────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateConversationAndRespond = channel.unary_stream(
                '/grok_api.Chat/CreateConversationAndRespond',
                request_serializer=grok__api__pb2.CreateConversationAndRespondRequest.SerializeToString,
                response_deserializer=grok__api__pb2.CreateConversationAndRespondResponseChunk.FromString,
                _registered_method=True)
        self.GetConversationStarters = channel.unary_unary(
                '/grok_api.Chat/GetConversationStarters',
                request_serializer=grok__api__pb2.EmptyRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetConversationStartersResponse.FromString,
                _registered_method=True)


class ChatServicer(object):
    """── Chat ─────────────────────────────────────────────────────────────────────
    """

    def CreateConversationAndRespond(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversationStarters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateConversationAndRespond': grpc.unary_stream_rpc_method_handler(
                    servicer.CreateConversationAndRespond,
                    request_deserializer=grok__api__pb2.CreateConversationAndRespondRequest.FromString,
                    response_serializer=grok__api__pb2.CreateConversationAndRespondResponseChunk.SerializeToString,
            ),
            'GetConversationStarters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationStarters,
                    request_deserializer=grok__api__pb2.EmptyRequest.FromString,
                    response_serializer=grok__api__pb2.GetConversationStartersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grok_api.Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grok_api.Chat', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """── Chat ─────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def CreateConversationAndRespond(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grok_api.Chat/CreateConversationAndRespond',
            grok__api__pb2.CreateConversationAndRespondRequest.SerializeToString,
            grok__api__pb2.CreateConversationAndRespondResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversationStarters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Chat/GetConversationStarters',
            grok__api__pb2.EmptyRequest.SerializeToString,
            grok__api__pb2.GetConversationStartersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelsStub(object):
    """── Models ───────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModels = channel.unary_unary(
                '/grok_api.Models/GetModels',
                request_serializer=grok__api__pb2.EmptyRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetModelsResponse.FromString,
                _registered_method=True)
        self.ListModes = channel.unary_unary(
                '/grok_api.Models/ListModes',
                request_serializer=grok__api__pb2.ListModesRequest.SerializeToString,
                response_deserializer=grok__api__pb2.ListModesResponse.FromString,
                _registered_method=True)
        self.GetModelsImagineOverrides = channel.unary_unary(
                '/grok_api.Models/GetModelsImagineOverrides',
                request_serializer=grok__api__pb2.EmptyRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetModelsImagineOverridesResponse.FromString,
                _registered_method=True)


class ModelsServicer(object):
    """── Models ───────────────────────────────────────────────────────────────────
    """

    def GetModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelsImagineOverrides(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModels,
                    request_deserializer=grok__api__pb2.EmptyRequest.FromString,
                    response_serializer=grok__api__pb2.GetModelsResponse.SerializeToString,
            ),
            'ListModes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModes,
                    request_deserializer=grok__api__pb2.ListModesRequest.FromString,
                    response_serializer=grok__api__pb2.ListModesResponse.SerializeToString,
            ),
            'GetModelsImagineOverrides': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelsImagineOverrides,
                    request_deserializer=grok__api__pb2.EmptyRequest.FromString,
                    response_serializer=grok__api__pb2.GetModelsImagineOverridesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grok_api.Models', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grok_api.Models', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Models(object):
    """── Models ───────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def GetModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Models/GetModels',
            grok__api__pb2.EmptyRequest.SerializeToString,
            grok__api__pb2.GetModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Models/ListModes',
            grok__api__pb2.ListModesRequest.SerializeToString,
            grok__api__pb2.ListModesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelsImagineOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Models/GetModelsImagineOverrides',
            grok__api__pb2.EmptyRequest.SerializeToString,
            grok__api__pb2.GetModelsImagineOverridesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FinanceStub(object):
    """── Finance ──────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindStock = channel.unary_unary(
                '/grok_api.Finance/FindStock',
                request_serializer=grok__api__pb2.FindStockRequest.SerializeToString,
                response_deserializer=grok__api__pb2.FindStockResponse.FromString,
                _registered_method=True)
        self.GetStockSummary = channel.unary_unary(
                '/grok_api.Finance/GetStockSummary',
                request_serializer=grok__api__pb2.GetStockTickerRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetStockSummaryResponse.FromString,
                _registered_method=True)
        self.GetStockMiniSummary = channel.unary_unary(
                '/grok_api.Finance/GetStockMiniSummary',
                request_serializer=grok__api__pb2.GetStockTickerRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetStockMiniSummaryResponse.FromString,
                _registered_method=True)
        self.GetStockChartData = channel.unary_unary(
                '/grok_api.Finance/GetStockChartData',
                request_serializer=grok__api__pb2.GetStockChartDataRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetStockChartDataResponse.FromString,
                _registered_method=True)
        self.GetRelatedTickers = channel.unary_unary(
                '/grok_api.Finance/GetRelatedTickers',
                request_serializer=grok__api__pb2.GetStockTickerRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetRelatedTickersResponse.FromString,
                _registered_method=True)
        self.GetStockFinancials = channel.unary_unary(
                '/grok_api.Finance/GetStockFinancials',
                request_serializer=grok__api__pb2.GetStockTickerRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetStockFinancialsResponse.FromString,
                _registered_method=True)


class FinanceServicer(object):
    """── Finance ──────────────────────────────────────────────────────────────────
    """

    def FindStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockMiniSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockChartData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelatedTickers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockFinancials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinanceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindStock': grpc.unary_unary_rpc_method_handler(
                    servicer.FindStock,
                    request_deserializer=grok__api__pb2.FindStockRequest.FromString,
                    response_serializer=grok__api__pb2.FindStockResponse.SerializeToString,
            ),
            'GetStockSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockSummary,
                    request_deserializer=grok__api__pb2.GetStockTickerRequest.FromString,
                    response_serializer=grok__api__pb2.GetStockSummaryResponse.SerializeToString,
            ),
            'GetStockMiniSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockMiniSummary,
                    request_deserializer=grok__api__pb2.GetStockTickerRequest.FromString,
                    response_serializer=grok__api__pb2.GetStockMiniSummaryResponse.SerializeToString,
            ),
            'GetStockChartData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockChartData,
                    request_deserializer=grok__api__pb2.GetStockChartDataRequest.FromString,
                    response_serializer=grok__api__pb2.GetStockChartDataResponse.SerializeToString,
            ),
            'GetRelatedTickers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelatedTickers,
                    request_deserializer=grok__api__pb2.GetStockTickerRequest.FromString,
                    response_serializer=grok__api__pb2.GetRelatedTickersResponse.SerializeToString,
            ),
            'GetStockFinancials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockFinancials,
                    request_deserializer=grok__api__pb2.GetStockTickerRequest.FromString,
                    response_serializer=grok__api__pb2.GetStockFinancialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grok_api.Finance', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grok_api.Finance', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Finance(object):
    """── Finance ──────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def FindStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Finance/FindStock',
            grok__api__pb2.FindStockRequest.SerializeToString,
            grok__api__pb2.FindStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Finance/GetStockSummary',
            grok__api__pb2.GetStockTickerRequest.SerializeToString,
            grok__api__pb2.GetStockSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockMiniSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Finance/GetStockMiniSummary',
            grok__api__pb2.GetStockTickerRequest.SerializeToString,
            grok__api__pb2.GetStockMiniSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockChartData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Finance/GetStockChartData',
            grok__api__pb2.GetStockChartDataRequest.SerializeToString,
            grok__api__pb2.GetStockChartDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelatedTickers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Finance/GetRelatedTickers',
            grok__api__pb2.GetStockTickerRequest.SerializeToString,
            grok__api__pb2.GetRelatedTickersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockFinancials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Finance/GetStockFinancials',
            grok__api__pb2.GetStockTickerRequest.SerializeToString,
            grok__api__pb2.GetStockFinancialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RateLimitsStub(object):
    """── RateLimits ───────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRateLimits = channel.unary_unary(
                '/grok_api.RateLimits/GetRateLimits',
                request_serializer=grok__api__pb2.GetRateLimitsRequest.SerializeToString,
                response_deserializer=grok__api__pb2.GetRateLimitsResponse.FromString,
                _registered_method=True)


class RateLimitsServicer(object):
    """── RateLimits ───────────────────────────────────────────────────────────────
    """

    def GetRateLimits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateLimitsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRateLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRateLimits,
                    request_deserializer=grok__api__pb2.GetRateLimitsRequest.FromString,
                    response_serializer=grok__api__pb2.GetRateLimitsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grok_api.RateLimits', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grok_api.RateLimits', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateLimits(object):
    """── RateLimits ───────────────────────────────────────────────────────────────
    """

    @staticmethod
    def GetRateLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.RateLimits/GetRateLimits',
            grok__api__pb2.GetRateLimitsRequest.SerializeToString,
            grok__api__pb2.GetRateLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SettingsStub(object):
    """── Settings ─────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserSettings = channel.unary_unary(
                '/grok_api.Settings/GetUserSettings',
                request_serializer=grok__api__pb2.EmptyRequest.SerializeToString,
                response_deserializer=grok__api__pb2.UserSettings.FromString,
                _registered_method=True)


class SettingsServicer(object):
    """── Settings ─────────────────────────────────────────────────────────────────
    """

    def GetUserSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSettings,
                    request_deserializer=grok__api__pb2.EmptyRequest.FromString,
                    response_serializer=grok__api__pb2.UserSettings.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grok_api.Settings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grok_api.Settings', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Settings(object):
    """── Settings ─────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def GetUserSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Settings/GetUserSettings',
            grok__api__pb2.EmptyRequest.SerializeToString,
            grok__api__pb2.UserSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SkillsStub(object):
    """── Skills ───────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSkills = channel.unary_unary(
                '/grok_api.Skills/ListSkills',
                request_serializer=grok__api__pb2.ListSkillsRequest.SerializeToString,
                response_deserializer=grok__api__pb2.ListSkillsResponse.FromString,
                _registered_method=True)


class SkillsServicer(object):
    """── Skills ───────────────────────────────────────────────────────────────────
    """

    def ListSkills(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkillsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=grok__api__pb2.ListSkillsRequest.FromString,
                    response_serializer=grok__api__pb2.ListSkillsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grok_api.Skills', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grok_api.Skills', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Skills(object):
    """── Skills ───────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Skills/ListSkills',
            grok__api__pb2.ListSkillsRequest.SerializeToString,
            grok__api__pb2.ListSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VoiceStub(object):
    """── Voice ────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTopVoices = channel.unary_unary(
                '/grok_api.Voice/ListTopVoices',
                request_serializer=grok__api__pb2.ListTopVoicesRequest.SerializeToString,
                response_deserializer=grok__api__pb2.ListTopVoicesResponse.FromString,
                _registered_method=True)
        self.ListVoices = channel.unary_unary(
                '/grok_api.Voice/ListVoices',
                request_serializer=grok__api__pb2.ListVoicesRequest.SerializeToString,
                response_deserializer=grok__api__pb2.ListVoicesResponse.FromString,
                _registered_method=True)
        self.SearchVoices = channel.unary_unary(
                '/grok_api.Voice/SearchVoices',
                request_serializer=grok__api__pb2.SearchVoicesRequest.SerializeToString,
                response_deserializer=grok__api__pb2.SearchVoicesResponse.FromString,
                _registered_method=True)


class VoiceServicer(object):
    """── Voice ────────────────────────────────────────────────────────────────────
    """

    def ListTopVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTopVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopVoices,
                    request_deserializer=grok__api__pb2.ListTopVoicesRequest.FromString,
                    response_serializer=grok__api__pb2.ListTopVoicesResponse.SerializeToString,
            ),
            'ListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVoices,
                    request_deserializer=grok__api__pb2.ListVoicesRequest.FromString,
                    response_serializer=grok__api__pb2.ListVoicesResponse.SerializeToString,
            ),
            'SearchVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVoices,
                    request_deserializer=grok__api__pb2.SearchVoicesRequest.FromString,
                    response_serializer=grok__api__pb2.SearchVoicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grok_api.Voice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grok_api.Voice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Voice(object):
    """── Voice ────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def ListTopVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Voice/ListTopVoices',
            grok__api__pb2.ListTopVoicesRequest.SerializeToString,
            grok__api__pb2.ListTopVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Voice/ListVoices',
            grok__api__pb2.ListVoicesRequest.SerializeToString,
            grok__api__pb2.ListVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grok_api.Voice/SearchVoices',
            grok__api__pb2.SearchVoicesRequest.SerializeToString,
            grok__api__pb2.SearchVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SuggestionServiceStub(object):
    """── SuggestionService ────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSuggestions = channel.unary_stream(
                '/grok_api.SuggestionService/StreamSuggestions',
                request_serializer=grok__api__pb2.StreamSuggestionsRequest.SerializeToString,
                response_deserializer=grok__api__pb2.StreamSuggestionsResponse.FromString,
                _registered_method=True)


class SuggestionServiceServicer(object):
    """── SuggestionService ────────────────────────────────────────────────────────
    """

    def StreamSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSuggestions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSuggestions,
                    request_deserializer=grok__api__pb2.StreamSuggestionsRequest.FromString,
                    response_serializer=grok__api__pb2.StreamSuggestionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grok_api.SuggestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grok_api.SuggestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuggestionService(object):
    """── SuggestionService ────────────────────────────────────────────────────────
    """

    @staticmethod
    def StreamSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grok_api.SuggestionService/StreamSuggestions',
            grok__api__pb2.StreamSuggestionsRequest.SerializeToString,
            grok__api__pb2.StreamSuggestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
